@@include('header.js');
@@include('dynamic-adaptive.js');
@@include('anchors.js');
@@include('team-slider.js');
@@include('testimonials-slider.js');
@@include('camp-slider.js');
@@include('js-tabs.js');
@@include('review-slider.js');
@@include('popup.js');
